/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#1f2020",
        "tertiary-dim": "#eabdcd",
        "error-container": "#7f2737",
        "on-tertiary": "#6c4a57",
        "primary-fixed": "#ffdad7",
        "background": "#0e0e0e",
        "on-surface-variant": "#acabaa",
        "on-secondary": "#251f1e",
        "surface-bright": "#2c2c2c",
        "secondary-dim": "#a79b9a",
        "outline": "#767575",
        "secondary-fixed-dim": "#ded2d0",
        "on-secondary-container": "#c9bdbb",
        "on-primary-fixed": "#850011",
        "inverse-surface": "#fcf9f8",
        "surface-container-lowest": "#000000",
        "on-background": "#e7e5e4",
        "on-tertiary-fixed-variant": "#6d4a57",
        "primary-dim": "#ff9f99",
        "on-secondary-fixed-variant": "#625958",
        "on-secondary-fixed": "#453e3c",
        "surface-variant": "#252626",
        "inverse-primary": "#bb1925",
        "inverse-on-surface": "#565555",
        "secondary-container": "#413a38",
        "error-dim": "#b95463",
        "on-primary-container": "#ffc1bd",
        "surface-container-low": "#131313",
        "on-error-container": "#ff97a3",
        "surface-container-highest": "#252626",
        "primary-container": "#930014",
        "outline-variant": "#484848",
        "on-primary": "#860012",
        "on-error": "#490013",
        "tertiary-container": "#f9cbdb",
        "secondary": "#a79b9a",
        "secondary-fixed": "#ede0dd",
        "primary": "#ffb3ae",
        "tertiary-fixed": "#f9cbdb",
        "surface-tint": "#ffb3ae",
        "surface-dim": "#0e0e0e",
        "surface": "#0e0e0e",
        "on-tertiary-container": "#63414e",
        "tertiary": "#ffdce7",
        "on-tertiary-fixed": "#4e2f3b",
        "on-surface": "#e7e5e4",
        "tertiary-fixed-dim": "#eabdcd",
        "on-primary-fixed-variant": "#b61422",
        "error": "#ec7c8a",
        "surface-container": "#191a1a",
        "primary-fixed-dim": "#ffc7c3"
      },
      fontFamily: {
        "headline": ["Inter"],
        "display": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "display-lg": ["Montserrat"],
        "title-md": ["Montserrat"],
        "body-sm": ["Inter"],
        "label-caps": ["Montserrat"],
        "body-lg": ["Inter"],
        "headline-lg": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"]
      },
      spacing: {
        "section-margin": "4rem",
        "card-gap": "1rem",
        "container-padding": "2rem",
        "gutter": "1.5rem"
      }
    },
  },
  plugins: [],
}
